### ISSUE TITLE
Create JSON format for sprite loading

### ISSUE THREAD

**Issue by bmhm** [alttpj/MemeforceHunt#14]
sth like this:

```json
{
  "sprites": [ 
    {
      "id": "ULID",
      "author": "author",
      "spriteName": "spriteName",
      "uri": "uri",
      "preview": "uri",
      "created": "createdTimeStamp"
    },
    {
      "id": "ULID",
      "author": "author",
      "spriteName": "spriteName",
      "uri": "uri",
      "preview": "uri",
      "created": "createdTimeStamp"
    }
  ]
}
```

This can be used in the default (shipped) sprites, an online repository or for adding new sprites, etc.

ULID: https://github.com/huxi/sulky/tree/master/sulky-ulid

**Comment by bmhm** [comment]
Well it became YAML after all.

Current format:

```yaml
---
sprites:
  - id: 01E6F3YXSW5A3AB0X4A1ACX0FN
    author: unknown
    spriteName: 1up
    uri: "/gfx/1up.bin"
    preview: "/previews/1up.png"
    created: '2020-04-21T21:38:11+02:00'
    palette: 'GREEN'
  - id: 01E6F3YXT1SFAWKQBEYG77VYBQ
    author: unknown
    spriteName: '69'
    uri: "/gfx/69.bin"
    preview: "/previews/69.png"
    created: '2020-04-21T21:38:11+02:00'
    palette: 'GREEN'
```
