### ISSUE TITLE
new item sprite file format

### ISSUE THREAD

**Issue by bmarwell** [alttpj/MemeforceHunt#23]
Instead of saving just the binary dump and the palette and description extra, I'd like to create a more specific format.

For easiness of use, that would be yaml with the following fields:

* ULID
* ~Sprite name (max 12 chars, only alphanumeric)~
* Display Name - should reflect the sprite name, but with spaces and more characters. 
  * E.g. if the sprite name is "B", the display name would be "[B]".
* Sprite author
* Description (optional)
* Creation date (optional)
* Base 64 encoded data, 4 uncompressed, packed tiles in one string or as 4 uncompressed, packed tiles separately
  * if it was 4 tiles in a single byte stream, that would be 90 uncompressed bytes
  * 90 raw bytes are 120 bytes in base64
* Base64 encoded png preview (optional, because it can be generated from the data).
* Colour palette name
* Tags[] (for search)

For later: Also supported gzipped extensions if it makes a difference.
This will also help creating an online repository or exchanging sprites.

Sprite name should be removed. The former idea was that it should reflect the filename.

**TODO:**

 - [x] Retain tags
 - [x] retain ULID

**Comment by bmhm** [comment]
```yaml
ulid: 01E936F3BP9TMJ35QRA4T7GYY1
displayName: 'A red something'
description: 'A quick drawing with the red palette colour in the GREEN palette."
author: "It's a me, Mario"
data: !!binary |-
  AAAAAAAAAAAAAAAHAAgAEAAAAAAAAAAAAAAAAAAAADAAeADIAAgACAAAAAAAAAAAABgACAAOAAMAAAAAAAAAAAAAAAAAAAAAABgAMABgAMAAAAAAAAAAAAAAAAAAAAAA
palette: GREEN
timestamp: '2020-05-24T11:18:11.062Z'
tags:
  - red
  - something
  - drawing
```
